spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: message
          uri: lb://message
          predicates:
            - Path=/message/**
          filters:
            - StripPrefix=1